services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: cashy
      POSTGRES_PASSWORD: cashy
      POSTGRES_DB: cashy
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
